"""campos descriptivos de convocatoria

Revision ID: 78e7cf8262b6
Revises: d4a23aec5eff
Create Date: 2026-08-17 13:00:57.222153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e7cf8262b6'
down_revision = 'd4a23aec5eff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convocations', sa.Column('es_en_sede', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('convocations', sa.Column('requisitos_texto', sa.String(), nullable=False, server_default=''))
    op.add_column('convocations', sa.Column('deseable_texto', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convocations', 'deseable_texto')
    op.drop_column('convocations', 'requisitos_texto')
    op.drop_column('convocations', 'es_en_sede')
    # ### end Alembic commands ###
